### ISSUE TITLE
[レイアウト]Deleteジェスチャーの実装

### ISSUE THREAD

**Issue by yuukikobori** [tikuwattoVX/DataPocket#13]
フリック、もしくはボタンによるレコードのDelete操作の実装

Delete用APIについては別途参照

**Comment by masaki-sakamoto** [comment]
良さげなサイトを見つけたので、それを参考にコーディングしてみやすわ。
[android スワイプ削除](http://yusuke-hata.hatenablog.com/entry/2014/01/16/021853)

**Comment by masaki-sakamoto** [comment]
なんとか見てくれは出来てきたけど、クリック判定がわからず苦戦してます。
![2015-05-04 22 50 39](https://cloud.githubusercontent.com/assets/11702269/7454607/575723a4-f2b0-11e4-8836-8d8f99aad611.png)

**Comment by masaki-sakamoto** [comment]
# スワイプ削除完成しました。

> クリック処理を実装。
> ジャンル画面とリスト画面に実装済。
> ボタンのデザインを浮かせた感じにしました。
> ![2015-05-05 22 47 02](https://cloud.githubusercontent.com/assets/11702269/7473921/5eb70f32-f379-11e4-9d04-a2adf98f7741.png)
