### ISSUE TITLE
役割分担

### ISSUE THREAD

**Issue by yuukikobori** [tikuwattoVX/DataPocket#4]
・xmlによるレイアウトの作成等の役割分担

**Comment by yuukikobori** [comment]
issue

**Comment by masaki-sakamoto** [comment]
やはり、xmlとjavaで一旦別れて作業し始めた方がいいのかね？

**Comment by masaki-sakamoto** [comment]
じゃあ私レイアウトからやってみます。
作ったファイルはlayoutフォルダに打ち込んでいきますよ。

**Comment by yuukikobori** [comment]
ファイル名

# javaファイル
- app/java/AddGenreActivity.java //ジャンル追加画面
- app/java/AddListActivity.java //リスト追加画面
- app/java/CustomAllActivity.java //設定画面（ジャンル、リスト、詳細）
- app/java/CustomListActivity.java //設定画面（リスト）
- app/java/DetailActivity.java //詳細画面
- app/java/GenreTopActivity.java //ジャンルトップ画面
- app/java/ListActivity.java //リスト
- app/java/Item.java //ゴミ
- app/java/MainActivity.java //ゴミ

**Comment by masaki-sakamoto** [comment]
# MarkDown

## テストです
- その１
- その２
- その３

**Comment by masaki-sakamoto** [comment]
![morio](https://cloud.githubusercontent.com/assets/11702269/6995871/6fd99c36-db9f-11e4-82ce-d626da2389a2.png)

**Comment by masaki-sakamoto** [comment]
コーディングをジャンル画面から少しずつやっていこうと思います。
一日一歩、三日で三歩。

**Comment by masaki-sakamoto** [comment]
ActionBarActivityがうまく使えないので、現状は従来のActivityからActionBarを操作する方向にしました。
